/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForPhotographersRouteImport } from './routes/for-photographers'
import { Route as ForClientsRouteImport } from './routes/for-clients'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as PhotographersJoinRouteImport } from './routes/photographers/join'
import { Route as PhotographersUsernameRouteImport } from './routes/photographers/$username'
import { Route as DashboardWhatsappTemplatesRouteImport } from './routes/dashboard.whatsapp-templates'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProductionRouteImport } from './routes/dashboard.production'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardContractsRouteImport } from './routes/dashboard.contracts'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as ContractsTokenRouteImport } from './routes/contracts.$token'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminPhotographersRouteImport } from './routes/admin.photographers'
import { Route as DashboardBookingsIndexRouteImport } from './routes/dashboard.bookings.index'
import { Route as DashboardBookingsIdRouteImport } from './routes/dashboard.bookings.$id'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'
import { Route as ApiPublicHooksPaymentRouteImport } from './routes/api/public/hooks/payment'
import { Route as ApiPublicHooksIcalSyncRouteImport } from './routes/api/public/hooks/ical-sync'
import { Route as ApiPublicHooksEmailRemindersRouteImport } from './routes/api/public/hooks/email-reminders'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPhotographersRoute = ForPhotographersRouteImport.update({
  id: '/for-photographers',
  path: '/for-photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClientsRoute = ForClientsRouteImport.update({
  id: '/for-clients',
  path: '/for-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersJoinRoute = PhotographersJoinRouteImport.update({
  id: '/photographers/join',
  path: '/photographers/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersUsernameRoute = PhotographersUsernameRouteImport.update({
  id: '/photographers/$username',
  path: '/photographers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappTemplatesRoute =
  DashboardWhatsappTemplatesRouteImport.update({
    id: '/whatsapp-templates',
    path: '/whatsapp-templates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductionRoute = DashboardProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const ContractsTokenRoute = ContractsTokenRouteImport.update({
  id: '/contracts/$token',
  path: '/contracts/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotographersRoute = AdminPhotographersRouteImport.update({
  id: '/photographers',
  path: '/photographers',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardBookingsIndexRoute = DashboardBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const DashboardBookingsIdRoute = DashboardBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPaymentRoute = ApiPublicHooksPaymentRouteImport.update({
  id: '/api/public/hooks/payment',
  path: '/api/public/hooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIcalSyncRoute = ApiPublicHooksIcalSyncRouteImport.update({
  id: '/api/public/hooks/ical-sync',
  path: '/api/public/hooks/ical-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmailRemindersRoute =
  ApiPublicHooksEmailRemindersRouteImport.update({
    id: '/api/public/hooks/email-reminders',
    path: '/api/public/hooks/email-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-clients': typeof ForClientsRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/whatsapp-templates': typeof DashboardWhatsappTemplatesRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$token': typeof ReviewTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/api/public/hooks/email-reminders': typeof ApiPublicHooksEmailRemindersRoute
  '/api/public/hooks/ical-sync': typeof ApiPublicHooksIcalSyncRoute
  '/api/public/hooks/payment': typeof ApiPublicHooksPaymentRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-clients': typeof ForClientsRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/whatsapp-templates': typeof DashboardWhatsappTemplatesRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$token': typeof ReviewTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/bookings': typeof DashboardBookingsIndexRoute
  '/api/public/hooks/email-reminders': typeof ApiPublicHooksEmailRemindersRoute
  '/api/public/hooks/ical-sync': typeof ApiPublicHooksIcalSyncRoute
  '/api/public/hooks/payment': typeof ApiPublicHooksPaymentRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-clients': typeof ForClientsRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/photographers': typeof AdminPhotographersRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/dashboard/whatsapp-templates': typeof DashboardWhatsappTemplatesRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$token': typeof ReviewTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/api/public/hooks/email-reminders': typeof ApiPublicHooksEmailRemindersRoute
  '/api/public/hooks/ical-sync': typeof ApiPublicHooksIcalSyncRoute
  '/api/public/hooks/payment': typeof ApiPublicHooksPaymentRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-clients'
    | '/for-photographers'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/photographers'
    | '/admin/refunds'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/production'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reports'
    | '/dashboard/subscription'
    | '/dashboard/whatsapp-templates'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$token'
    | '/track/$token'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/bookings/$id'
    | '/dashboard/bookings/'
    | '/api/public/hooks/email-reminders'
    | '/api/public/hooks/ical-sync'
    | '/api/public/hooks/payment'
    | '/api/public/ical/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/faq'
    | '/for-clients'
    | '/for-photographers'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/photographers'
    | '/admin/refunds'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/production'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reports'
    | '/dashboard/subscription'
    | '/dashboard/whatsapp-templates'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$token'
    | '/track/$token'
    | '/admin'
    | '/dashboard'
    | '/dashboard/bookings/$id'
    | '/dashboard/bookings'
    | '/api/public/hooks/email-reminders'
    | '/api/public/hooks/ical-sync'
    | '/api/public/hooks/payment'
    | '/api/public/ical/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-clients'
    | '/for-photographers'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/photographers'
    | '/admin/refunds'
    | '/admin/reviews'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/production'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reports'
    | '/dashboard/subscription'
    | '/dashboard/whatsapp-templates'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$token'
    | '/track/$token'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/bookings/$id'
    | '/dashboard/bookings/'
    | '/api/public/hooks/email-reminders'
    | '/api/public/hooks/ical-sync'
    | '/api/public/hooks/payment'
    | '/api/public/ical/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForClientsRoute: typeof ForClientsRoute
  ForPhotographersRoute: typeof ForPhotographersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ContractsTokenRoute: typeof ContractsTokenRoute
  PhotographersUsernameRoute: typeof PhotographersUsernameRoute
  PhotographersJoinRoute: typeof PhotographersJoinRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  TrackTokenRoute: typeof TrackTokenRoute
  ApiPublicHooksEmailRemindersRoute: typeof ApiPublicHooksEmailRemindersRoute
  ApiPublicHooksIcalSyncRoute: typeof ApiPublicHooksIcalSyncRoute
  ApiPublicHooksPaymentRoute: typeof ApiPublicHooksPaymentRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-photographers': {
      id: '/for-photographers'
      path: '/for-photographers'
      fullPath: '/for-photographers'
      preLoaderRoute: typeof ForPhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clients': {
      id: '/for-clients'
      path: '/for-clients'
      fullPath: '/for-clients'
      preLoaderRoute: typeof ForClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/join': {
      id: '/photographers/join'
      path: '/photographers/join'
      fullPath: '/photographers/join'
      preLoaderRoute: typeof PhotographersJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/$username': {
      id: '/photographers/$username'
      path: '/photographers/$username'
      fullPath: '/photographers/$username'
      preLoaderRoute: typeof PhotographersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp-templates': {
      id: '/dashboard/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/dashboard/whatsapp-templates'
      preLoaderRoute: typeof DashboardWhatsappTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/production': {
      id: '/dashboard/production'
      path: '/production'
      fullPath: '/dashboard/production'
      preLoaderRoute: typeof DashboardProductionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/contracts/$token': {
      id: '/contracts/$token'
      path: '/contracts/$token'
      fullPath: '/contracts/$token'
      preLoaderRoute: typeof ContractsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photographers': {
      id: '/admin/photographers'
      path: '/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof AdminPhotographersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/bookings/': {
      id: '/dashboard/bookings/'
      path: '/'
      fullPath: '/dashboard/bookings/'
      preLoaderRoute: typeof DashboardBookingsIndexRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/bookings/$id': {
      id: '/dashboard/bookings/$id'
      path: '/$id'
      fullPath: '/dashboard/bookings/$id'
      preLoaderRoute: typeof DashboardBookingsIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payment': {
      id: '/api/public/hooks/payment'
      path: '/api/public/hooks/payment'
      fullPath: '/api/public/hooks/payment'
      preLoaderRoute: typeof ApiPublicHooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ical-sync': {
      id: '/api/public/hooks/ical-sync'
      path: '/api/public/hooks/ical-sync'
      fullPath: '/api/public/hooks/ical-sync'
      preLoaderRoute: typeof ApiPublicHooksIcalSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-reminders': {
      id: '/api/public/hooks/email-reminders'
      path: '/api/public/hooks/email-reminders'
      fullPath: '/api/public/hooks/email-reminders'
      preLoaderRoute: typeof ApiPublicHooksEmailRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPhotographersRoute: typeof AdminPhotographersRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPhotographersRoute: AdminPhotographersRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardBookingsRouteChildren {
  DashboardBookingsIdRoute: typeof DashboardBookingsIdRoute
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsIdRoute: DashboardBookingsIdRoute,
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardProductionRoute: typeof DashboardProductionRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardWhatsappTemplatesRoute: typeof DashboardWhatsappTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardProductionRoute: DashboardProductionRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardWhatsappTemplatesRoute: DashboardWhatsappTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForClientsRoute: ForClientsRoute,
  ForPhotographersRoute: ForPhotographersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ContractsTokenRoute: ContractsTokenRoute,
  PhotographersUsernameRoute: PhotographersUsernameRoute,
  PhotographersJoinRoute: PhotographersJoinRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  TrackTokenRoute: TrackTokenRoute,
  ApiPublicHooksEmailRemindersRoute: ApiPublicHooksEmailRemindersRoute,
  ApiPublicHooksIcalSyncRoute: ApiPublicHooksIcalSyncRoute,
  ApiPublicHooksPaymentRoute: ApiPublicHooksPaymentRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
