/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewBookingIdRouteImport } from './routes/review.$bookingId'
import { Route as PhotographersJoinRouteImport } from './routes/photographers/join'
import { Route as PhotographersUsernameRouteImport } from './routes/photographers/$username'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardContractsRouteImport } from './routes/dashboard.contracts'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as ContractsTokenRouteImport } from './routes/contracts.$token'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as DashboardBookingsIdRouteImport } from './routes/dashboard.bookings.$id'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewBookingIdRoute = ReviewBookingIdRouteImport.update({
  id: '/review/$bookingId',
  path: '/review/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersJoinRoute = PhotographersJoinRouteImport.update({
  id: '/photographers/join',
  path: '/photographers/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersUsernameRoute = PhotographersUsernameRouteImport.update({
  id: '/photographers/$username',
  path: '/photographers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const ContractsTokenRoute = ContractsTokenRouteImport.update({
  id: '/contracts/$token',
  path: '/contracts/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsIdRoute = DashboardBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/contracts/$token': typeof ContractsTokenRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/photographers/$username': typeof PhotographersUsernameRoute
  '/photographers/join': typeof PhotographersJoinRoute
  '/review/$bookingId': typeof ReviewBookingIdRoute
  '/dashboard/bookings/$id': typeof DashboardBookingsIdRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/subscription'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$bookingId'
    | '/dashboard/bookings/$id'
    | '/api/public/ical/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/subscription'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$bookingId'
    | '/dashboard/bookings/$id'
    | '/api/public/ical/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/subscriptions'
    | '/contracts/$token'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/contracts'
    | '/dashboard/pricing'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/subscription'
    | '/photographers/$username'
    | '/photographers/join'
    | '/review/$bookingId'
    | '/dashboard/bookings/$id'
    | '/api/public/ical/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  ContractsTokenRoute: typeof ContractsTokenRoute
  PhotographersUsernameRoute: typeof PhotographersUsernameRoute
  PhotographersJoinRoute: typeof PhotographersJoinRoute
  ReviewBookingIdRoute: typeof ReviewBookingIdRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$bookingId': {
      id: '/review/$bookingId'
      path: '/review/$bookingId'
      fullPath: '/review/$bookingId'
      preLoaderRoute: typeof ReviewBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/join': {
      id: '/photographers/join'
      path: '/photographers/join'
      fullPath: '/photographers/join'
      preLoaderRoute: typeof PhotographersJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers/$username': {
      id: '/photographers/$username'
      path: '/photographers/$username'
      fullPath: '/photographers/$username'
      preLoaderRoute: typeof PhotographersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/contracts/$token': {
      id: '/contracts/$token'
      path: '/contracts/$token'
      fullPath: '/contracts/$token'
      preLoaderRoute: typeof ContractsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings/$id': {
      id: '/dashboard/bookings/$id'
      path: '/$id'
      fullPath: '/dashboard/bookings/$id'
      preLoaderRoute: typeof DashboardBookingsIdRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardBookingsRouteChildren {
  DashboardBookingsIdRoute: typeof DashboardBookingsIdRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsIdRoute: DashboardBookingsIdRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  ContractsTokenRoute: ContractsTokenRoute,
  PhotographersUsernameRoute: PhotographersUsernameRoute,
  PhotographersJoinRoute: PhotographersJoinRoute,
  ReviewBookingIdRoute: ReviewBookingIdRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
